spring:
  application:
    name: debezium-rag

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.2
      embedding:
        options:
          model: text-embedding-3-small

server:
  port: 8080

logging:
  level:
    com.ankit.zerodha: INFO
    org.springframework.ai: INFO
