spring:
  application:
    name: debezium-rag

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2
      embedding:
        options:
          model: nomic-embed-text

server:
  port: 8080

logging:
  level:
    com.ankit.debezium: INFO
    org.springframework.ai: INFO
